name: ai_interviewer
description: A new Flutter project for AI Interviewer.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_animate: ^4.2.0
  provider: ^6.0.5
  font_awesome_flutter: ^10.6.0
  firebase_core: any
  firebase_auth: any
  google_sign_in: any
  cloud_firestore: any
  video_player: any
  uuid: any
  camera: ^0.11.3
  permission_handler: ^12.0.1
  google_generative_ai: ^0.4.7
  flutter_tts: ^4.2.5
  speech_to_text: ^7.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/videos/
